function createIdentityOrder(rows, cols) { return Array.from({ length: rows * cols }, (_, i) => i) }
function shuffleDerangement(rows, cols, random) { const rnd = typeof random === 'function' ? random : Math.random; const n = rows * cols; const order = createIdentityOrder(rows, cols); if (n < 2) return order; for (let attempt = 0; attempt < 100; attempt++) { for (let i = n - 1; i > 0; i--) { const j = Math.floor(rnd() * (i + 1)); [order[i], order[j]] = [order[j], order[i]] } if (order.every((piece, i) => piece !== i)) return order } return order.map((_, i) => (i + 1) % n) }
function swapCells(order, a, b) { const next = order.slice(); [next[a], next[b]] = [next[b], next[a]]; return next }
function applyOperations(rows, cols, operations) { let order = createIdentityOrder(rows, cols); for (const op of operations || []) order = swapCells(order, op.cells[0], op.cells[1]); return order }
function isSolved(order) { return Array.isArray(order) && order.every((piece, i) => piece === i) }
function countMisplaced(order) { return order.reduce((n, piece, i) => n + (piece === i ? 0 : 1), 0) }
function isPermutation(order, size) { return Array.isArray(order) && order.length === size && new Set(order).size === size && order.every(x => Number.isInteger(x) && x >= 0 && x < size) }
function cellFromNormalizedPoint(x, y, rows, cols) { if (x < 0 || x > 1 || y < 0 || y > 1) return -1; return Math.min(rows - 1, Math.floor(y * rows)) * cols + Math.min(cols - 1, Math.floor(x * cols)) }
function findHintSwap(order) { const a = order.findIndex((piece, i) => piece !== i); if (a < 0) return null; const b = order.findIndex(piece => piece === a); return b < 0 ? null : [a, b] }
function puzzleGroups(order, rows, cols) { const seen=new Set(),groups=[];for(let start=0;start<order.length;start++){if(seen.has(start))continue;const group=[],queue=[start];seen.add(start);while(queue.length){const cell=queue.shift(),piece=order[cell];group.push(cell);for(const [dr,dc] of [[0,1],[1,0],[0,-1],[-1,0]]){const r=Math.floor(cell/cols),c=cell%cols,nr=r+dr,nc=c+dc;if(nr<0||nr>=rows||nc<0||nc>=cols)continue;const next=nr*cols+nc;if(seen.has(next))continue;const nextPiece=order[next];if(Math.floor(nextPiece/cols)-Math.floor(piece/cols)===dr&&nextPiece%cols-piece%cols===dc){seen.add(next);queue.push(next)}}}groups.push(group)}return groups }
function groupForCell(order, rows, cols, cell) { return puzzleGroups(order,rows,cols).find(group=>group.includes(cell))||[] }
function breaksAssembledGroup(order, next, rows, cols) { const before=puzzleGroups(order,rows,cols).filter(g=>g.length>1);if(!before.length)return false;const pieceGroup=new Map();puzzleGroups(next,rows,cols).forEach((g,i)=>{for(const c of g)pieceGroup.set(next[c],i)});for(const g of before){let id;for(const c of g){const gid=pieceGroup.get(order[c]);if(id===undefined)id=gid;else if(gid!==id)return true}}return false }
function movePuzzleGroup(order, rows, cols, sourceCell, targetCell) { const group=groupForCell(order,rows,cols,sourceCell);if(!group.length)return null;const sr=Math.floor(sourceCell/cols),sc=sourceCell%cols,tr=Math.floor(targetCell/cols),tc=targetCell%cols,dr=tr-sr,dc=tc-sc;if(!dr&&!dc)return null;const groupSet=new Set(group),targetSet=new Set();for(const cell of group){const r=Math.floor(cell/cols)+dr,c=cell%cols+dc;if(r<0||r>=rows||c<0||c>=cols)return null;targetSet.add(r*cols+c)}const delta=dr*cols+dc,next=order.slice();for(const cell of group)next[cell+delta]=order[cell];for(const cell of targetSet){if(groupSet.has(cell))continue;let landing=cell-delta;while(targetSet.has(landing))landing-=delta;next[landing]=order[cell]}if(breaksAssembledGroup(order,next,rows,cols))return null;return next }
function findHintMove(order, rows, cols) { for(let cell=0;cell<order.length;cell++){if(order[cell]===cell)continue;const moved=movePuzzleGroup(order,rows,cols,cell,order[cell]);if(moved)return{source:cell,target:order[cell],order:moved}}return null }
function validatePuzzleConfig(puzzle, allowEmpty = false, requireAllMisplaced = false) { if (!puzzle || !Number.isInteger(puzzle.rows) || !Number.isInteger(puzzle.cols) || puzzle.rows < 2 || puzzle.rows > 8 || puzzle.cols < 2 || puzzle.cols > 8 || puzzle.rows * puzzle.cols > 48) return { ok: false, error: 'LEVEL_PUZZLE_GRID_INVALID' }; const size=puzzle.rows*puzzle.cols;const ops = Array.isArray(puzzle.operations) ? puzzle.operations : []; if (ops.length > 24 || (!allowEmpty && ops.length < 1)) return { ok: false, error: 'LEVEL_PUZZLE_OPERATIONS_INVALID' }; const used = new Set(); for (const op of ops) { if (!op || op.type !== 'swap' || !Array.isArray(op.cells) || op.cells.length !== 2) return { ok: false, error: 'LEVEL_PUZZLE_OPERATION_INVALID' }; const [a,b] = op.cells; if (![a,b].every(Number.isInteger) || a === b || a < 0 || b < 0 || a >= size || b >= size || used.has(a) || used.has(b)) return { ok: false, error: 'LEVEL_PUZZLE_CELLS_INVALID' }; used.add(a); used.add(b) } if(requireAllMisplaced&&used.size!==size)return{ok:false,error:'LEVEL_PUZZLE_ALL_CELLS_MUST_BE_MISPLACED'};return { ok: true } }
module.exports = { createIdentityOrder, shuffleDerangement, swapCells, applyOperations, isSolved, countMisplaced, isPermutation, cellFromNormalizedPoint, findHintSwap, puzzleGroups, groupForCell, movePuzzleGroup, findHintMove, validatePuzzleConfig }
