const $=id=>document.getElementById(id),token=()=>sessionStorage.getItem('oddspot_admin_token')||'';
function toast(message){const el=$('toast');el.textContent=message;el.style.display='block';setTimeout(()=>el.style.display='none',2500)}
async function api(path,options={}){const response=await fetch('/api/v1'+path,{...options,headers:{'Content-Type':'application/json','X-Admin-Token':token(),...(options.headers||{})}});const data=response.status===204?{}:await response.json();if(!response.ok)throw new Error(data.error_code||`HTTP_${response.status}`);return data.data}
const transitions={draft:['generated'],generated:['pending_review','auto_review_failed'],auto_review_failed:['draft'],pending_review:['approved','auto_review_failed'],approved:['staging'],staging:['published','disabled'],published:['disabled'],disabled:['staging']};
async function loadLevels(){try{const q=$('status').value?`?status=${encodeURIComponent($('status').value)}`:'';const data=await api('/levels'+q),root=$('levels');root.replaceChildren();for(const item of data.items||[]){const row=document.createElement('div');row.className='level';const info=document.createElement('div');info.innerHTML=`<strong>${item.level_id}</strong> <span class="badge">v${item.version}</span><div class="muted">难度 ${item.difficulty} · 质量 ${item.quality_score}</div>`;const state=document.createElement('span');state.className='badge';state.textContent=item.status;const actions=document.createElement('select');actions.innerHTML='<option value="">转换状态…</option>'+((transitions[item.status]||[]).map(v=>`<option>${v}</option>`).join(''));actions.onchange=async()=>{if(!actions.value)return;try{await api(`/levels/${item.level_id}/versions/${item.version}/transition`,{method:'POST',body:JSON.stringify({to_status:actions.value,reviewer_id:'web-admin',reason:'CMS manual transition'})});toast('状态已更新');loadLevels()}catch(e){toast(e.message)}};row.append(info,state,actions);root.append(row)}}catch(e){toast(e.message)}}
async function loadReports(){try{const q=$('report-status').value?`?status=${encodeURIComponent($('report-status').value)}`:'';const data=await api('/reports'+q),root=$('reports');root.replaceChildren();for(const item of data.items||[]){const row=document.createElement('div');row.className='level';const info=document.createElement('div');info.innerHTML=`<strong>${item.level_id}</strong> <span class="badge">${item.category}</span><div class="muted">${item.description||'无说明'}</div>`;const actions=document.createElement('select');actions.innerHTML='<option value="">处理…</option><option>reviewing</option><option>resolved</option><option>dismissed</option>';actions.onchange=async()=>{if(!actions.value)return;try{await api(`/reports/${item.id}/resolve`,{method:'POST',body:JSON.stringify({status:actions.value,note:'CMS manual resolution'})});toast('举报状态已更新');loadReports();loadMetrics()}catch(e){toast(e.message)}};row.append(info,document.createTextNode(item.status),actions);root.append(row)}}catch(e){toast(e.message)}}
async function loadMetrics(){try{const m=await api('/metrics/summary');$('metrics').innerHTML=`<div class="level"><strong>用户 ${m.users}</strong><span>尝试 ${m.attempts}</span><span>完成率 ${(m.completion_rate*100).toFixed(1)}%</span><span>提示 ${m.hints_used}</span><span>已验证购买 ${m.purchases_verified}</span><span>待处理举报 ${m.open_reports}</span></div>`}catch(e){toast(e.message)}}
function loadAll(){loadLevels();loadReports();loadMetrics()}
$('save-token').onclick=()=>{sessionStorage.setItem('oddspot_admin_token',$('token').value);loadAll()};$('logout').onclick=()=>{sessionStorage.removeItem('oddspot_admin_token');toast('令牌已清除')};$('refresh').onclick=loadLevels;$('status').onchange=loadLevels;$('refresh-reports').onclick=loadReports;$('report-status').onchange=loadReports;$('refresh-metrics').onclick=loadMetrics;
$('create-job').onclick=async()=>{try{const input=JSON.parse($('job-input').value),body={id:$('job-id').value,market:'global',prompt_version:$('prompt-version').value,model:$('model').value,input};const job=await api('/generation/jobs',{method:'POST',body:JSON.stringify(body)});$('job-result').textContent=JSON.stringify(job,null,2);toast('任务已创建')}catch(e){toast(e.message)}};
if(token())loadAll();
