const $=id=>document.getElementById(id);
const state={catalog:[],assets:[],view:"overview",series:null,level:null,levelEntry:null,selected:0,dirty:false,adding:false};
const token=()=>sessionStorage.getItem("oddspot_admin_token")||"";
const apiBase=()=>localStorage.getItem("oddspot_admin_api")||`${location.origin}/admin/v1`;
const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const formatBytes=n=>n>1048576?`${(n/1048576).toFixed(1)} MB`:`${Math.ceil(n/1024)} KB`;

async function api(path,options={}){
  const response=await fetch(apiBase()+path,{...options,headers:{"X-Admin-Token":token(),...(options.headers||{})}});
  const body=await response.json().catch(()=>({}));
  if(!response.ok)throw new Error(body.message||body.error_code||`HTTP ${response.status}`);
  return body.data;
}
function toast(message,type=""){const el=$("toast");el.textContent=message;el.style.background=type==="error"?"#b42318":"#252b31";el.style.display="block";setTimeout(()=>el.style.display="none",2600)}
function setSave(text,dirty=false){state.dirty=dirty;$("save-state").textContent=text}
async function loadData(){const [catalog,assets]=await Promise.all([api("/catalog"),api("/assets")]);state.catalog=catalog.series||[];state.assets=assets.items||[]}

function shell(view,title){state.view=view;document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.view===view));$("breadcrumb").textContent=`工作台 / ${title}`}
function renderOverview(){
  shell("overview","总览");const levels=state.catalog.flatMap(s=>s.levels||[]);
  $("view").innerHTML=`<div class="page"><div class="page-header"><div><h1>Studio Overview</h1><p>内容生产与发布状态一览</p></div><button class="btn primary" onclick="newLevel()">＋ 新建关卡</button></div>
  <div class="stats"><div class="stat"><label>已发布系列</label><strong>${state.catalog.filter(s=>s.enabled).length}</strong><span class="trend">后台动态配置</span></div><div class="stat"><label>已发布关卡</label><strong>${levels.length}</strong><span class="trend">客户端实时拉取</span></div><div class="stat"><label>素材文件</label><strong>${state.assets.length}</strong><span class="trend">${formatBytes(state.assets.reduce((a,b)=>a+b.bytes,0))}</span></div><div class="stat"><label>待审核</label><strong>0</strong><span class="trend">当前无阻塞</span></div></div>
  <div class="dashboard-grid"><section class="card"><h2>关卡生产趋势</h2><div class="chart">${[34,51,42,67,58,81,74].map(h=>`<div class="bar" style="height:${h}%"></div>`).join("")}</div></section><section class="card"><h2>快捷操作</h2><div class="quick-grid"><button class="quick" onclick="showSeriesModal()">新建内容系列 <span>›</span></button><button class="quick" onclick="newLevel()">新建关卡 <span>›</span></button><button class="quick" onclick="navigate('library')">上传素材 <span>›</span></button></div></section></div>
  <section class="card" style="margin-top:16px"><h2>最近内容</h2>${levelTable(levels.slice(0,6))}</section></div>`;
}
function levelTable(levels,series){
  if(!levels.length)return`<div class="empty">暂无关卡</div>`;
  return `<table class="level-table"><thead><tr><th>预览</th><th>关卡</th><th>难度</th><th>答案</th><th>版本</th><th>状态</th><th></th></tr></thead><tbody>${levels.map(l=>`<tr><td><img class="thumb" src="${escapeHtml(l.thumbnail_url)}"></td><td><b>${escapeHtml(l.title)}</b><br><small>${escapeHtml(l.id)}</small></td><td>${"◆".repeat(l.difficulty||1)}</td><td>${l.difference_count}</td><td>v${l.version}</td><td><span class="badge published">已发布</span></td><td><button class="btn small" onclick="openEditorById('${l.id}','${series?.id||findSeries(l.id)?.id||""}')">编辑</button></td></tr>`).join("")}</tbody></table>`;
}
function renderSeries(){
  shell("series","内容系列");$("view").innerHTML=`<div class="page"><div class="page-header"><div><h1>内容系列</h1><p>管理所有游戏模式与系列内容</p></div><button class="btn primary" onclick="showSeriesModal()">＋ 新建系列</button></div><div class="filters"><input id="series-search" placeholder="搜索系列名称或 ID" oninput="filterSeries(this.value)"><select><option>全部状态</option><option>已启用</option><option>已停用</option></select></div><div id="series-list" class="series-list">${seriesRows(state.catalog)}</div></div>`;
}
function seriesRows(items){return items.map(s=>{const cover=s.cover_url||(s.levels?.[0]?.thumbnail_url||"");return`<article class="series-row" data-search="${escapeHtml((s.title+" "+s.id).toLowerCase())}"><img class="series-cover" src="${escapeHtml(cover)}"><div><h3>${escapeHtml(s.title)} <span class="badge ${s.enabled?"published":"draft"}">${s.enabled?"ACTIVE":"DISABLED"}</span></h3><div class="meta"><span>${s.levels?.length||0} 个关卡</span><span>${escapeHtml(s.mode)}</span><span>${escapeHtml(s.description||"暂无说明")}</span></div></div><div class="actions"><button class="btn small" onclick="openSeries('${s.id}')">查看关卡</button><button class="btn small" onclick="showSeriesModal('${s.id}')">编辑系列</button></div></article>`}).join("")||`<div class="empty">还没有系列，创建第一个系列吧</div>`}
function filterSeries(value){document.querySelectorAll(".series-row").forEach(x=>x.hidden=!x.dataset.search.includes(value.toLowerCase()))}
function openSeries(id){const s=state.catalog.find(x=>x.id===id);state.series=s;shell("series",s.title);$("view").innerHTML=`<div class="page"><div class="page-header"><div><button class="btn ghost" onclick="renderSeries()">← 返回系列</button><h1>${escapeHtml(s.title)}</h1><p>${escapeHtml(s.description)}</p></div><div class="actions"><button class="btn" onclick="showSeriesModal('${s.id}')">编辑系列</button><button class="btn primary" onclick="newLevel('${s.id}')">＋ 新建关卡</button></div></div><section class="card">${levelTable(s.levels||[],s)}</section></div>`}
function renderLevels(){shell("levels","关卡管理");$("view").innerHTML=`<div class="page"><div class="page-header"><div><h1>关卡管理</h1><p>跨系列查看与编辑全部关卡</p></div><button class="btn primary" onclick="newLevel()">＋ 新建关卡</button></div>${levelTable(state.catalog.flatMap(s=>s.levels||[]))}</div>`}
function renderLibrary(){
  shell("library","素材库");$("view").innerHTML=`<div class="page"><div class="page-header"><div><h1>素材库</h1><p>列表加载轻量缩略图，进入关卡后才加载原图</p></div><button class="btn primary" onclick="$('asset-file').click()">上传素材</button></div><div class="dropzone" onclick="$('asset-file').click()"><b>拖放或点击上传图片</b><p>PNG、JPG，最大 15 MB；上传后自动生成缩略图</p><input id="asset-file" type="file" accept="image/png,image/jpeg" hidden onchange="uploadLibraryAsset(this.files[0])"></div><div class="library-grid">${state.assets.map(a=>`<article class="asset-card"><img src="${escapeHtml(a.thumbnail_url||a.url)}" loading="lazy"><div class="asset-info"><b>${escapeHtml(a.name)}</b><small>原图 ${formatBytes(a.bytes)}${a.thumbnail_bytes?` · 缩略图 ${formatBytes(a.thumbnail_bytes)}`:""}</small><div style="margin-top:8px"><button class="btn small" onclick="navigator.clipboard.writeText('${escapeHtml(a.url)}');toast('原图 URL 已复制')">复制原图 URL</button></div></div></article>`).join("")}</div></div>`;
}
function renderPlaceholder(view,title,description){shell(view,title);$("view").innerHTML=`<div class="page"><div class="page-header"><div><h1>${title}</h1><p>${description}</p></div></div><div class="card empty">该模块已纳入 Studio 导航，将在对应数据接口完成后接入。</div></div>`}
function navigate(view){if(state.dirty&&!confirm("当前关卡有未保存修改，确定离开吗？"))return;({overview:renderOverview,series:renderSeries,levels:renderLevels,library:renderLibrary,review:()=>renderReview(),feedback:()=>renderPlaceholder("feedback","问题反馈","集中处理玩家上报的问题"),analytics:()=>renderPlaceholder("analytics","数据分析","查看完成率、提示使用与热点误触"),settings:()=>renderSettings()})[view]()}
function findSeries(levelId){return state.catalog.find(s=>(s.levels||[]).some(l=>l.id===levelId))}

async function openEditorById(levelId,seriesId){
  try{const data=await api(`/levels/${encodeURIComponent(levelId)}`);state.level=structuredClone(data);state.series=state.catalog.find(s=>s.id===seriesId)||findSeries(levelId);state.levelEntry=state.series?.levels.find(l=>l.id===levelId);state.selected=0;state.dirty=false;renderEditor()}catch(e){toast(e.message,"error")}
}
function renderEditor(){
  const l=state.level,diffs=l.differences||[],asset=l.assets?.image||{};shell("levels",`关卡编辑器 / ${l.title}`);
  $("view").innerHTML=`<div class="editor"><aside class="editor-left"><div class="editor-head"><h2>${escapeHtml(l.title)}</h2><small>${escapeHtml(l.level_id)} · v${l.level_version}</small></div><div class="panel-section"><div class="panel-title">关卡信息</div><div class="form-stack"><label>标题<input id="level-title" value="${escapeHtml(l.title)}" oninput="updateLevelField('title',this.value)"></label><label>所属系列<select id="editor-series" onchange="markDirty()">${state.catalog.map(s=>`<option value="${s.id}" ${s.id===state.series?.id?"selected":""}>${escapeHtml(s.title)}</option>`).join("")}</select></label><label>难度<select id="level-difficulty" onchange="updateDifficulty(this.value)">${[1,2,3,4,5].map(n=>`<option ${n===(l.difficulty?.total||1)?"selected":""}>${n}</option>`).join("")}</select></label></div></div><div class="panel-section"><div class="panel-title">答案热点 ${diffs.length}</div><div id="answer-list" class="answer-list">${answerList()}</div><button class="btn small" style="width:100%;margin-top:10px" onclick="addAnswer()">＋ 添加答案</button></div></aside>
  <section class="canvas-pane"><div class="canvas-toolbar"><div class="canvas-tools"><button class="btn small" onclick="state.adding=!state.adding;this.classList.toggle('primary',state.adding)">⌖ 标注工具</button><button class="btn small" onclick="toggleSafeZones()">安全区域</button><button class="btn small" onclick="fitImage()">适应窗口</button></div><span>${l.assets?.width||0} × ${l.assets?.height||0}</span></div><div class="canvas-workspace"><div id="image-stage" class="image-stage" onclick="canvasClick(event)"><img id="level-image" src="${escapeHtml(asset.url||asset.local_path||"")}" draggable="false">${hotspots()}<div class="safe-zone"></div><div class="safe-zone bottom"></div></div></div><footer class="editor-footer"><span id="editor-status">自动保存未启用 · 请手动保存</span><div class="actions"><button class="btn" onclick="showMobilePreview()">手机预览</button><button class="btn" onclick="saveLevel('draft')">保存草稿</button><button class="btn primary" onclick="showPublishModal()">发布关卡</button></div></footer></section><aside class="inspector" id="inspector">${inspector()}</aside></div>`;
  bindHotspotDrag();
}
function answerList(){return(state.level.differences||[]).map((d,i)=>`<div class="answer-item ${i===state.selected?"active":""}" onclick="selectAnswer(${i})"><span class="answer-number">${i+1}</span><div><b>${escapeHtml(d.label||d.id||"未命名答案")}</b><br><small>${escapeHtml(d.era||"未填写年代")}</small></div></div>`).join("")}
function hotspots(){return(state.level.differences||[]).map((d,i)=>{const radius=Math.max(3,(d.radius||.04)*100);return`<button class="hotspot ${i===state.selected?"selected":""}" data-index="${i}" style="left:${d.x*100}%;top:${d.y*100}%;width:${radius*2}%;aspect-ratio:1">${i+1}</button>`}).join("")}
function inspector(){const d=state.level.differences?.[state.selected];if(!d)return`<div class="empty">选择或添加一个答案热点</div>`;return`<div class="editor-head"><h2>热点属性</h2><small>${escapeHtml(d.id)}</small></div><div class="panel-section"><div class="panel-title">答案内容</div><div class="form-stack"><label>显示名称<input value="${escapeHtml(d.label||"")}" oninput="updateDiff('label',this.value)"></label><label>物品 ID<input value="${escapeHtml(d.id||"")}" oninput="updateDiff('id',this.value)"></label><label>出现年代<input value="${escapeHtml(d.era||"")}" oninput="updateDiff('era',this.value)"></label><label>为什么不属于当前年代<textarea oninput="updateDiff('explanation',this.value)">${escapeHtml(d.explanation||"")}</textarea></label><label>答案难度<select onchange="updateDiff('difficulty',Number(this.value))">${[1,2,3,4,5].map(n=>`<option ${n===(d.difficulty||1)?"selected":""}>${n}</option>`).join("")}</select></label></div></div><div class="panel-section"><div class="panel-title">坐标与容错</div><div class="coord-grid"><label>X<input type="number" step=".001" value="${d.x}" onchange="updateDiff('x',Number(this.value),true)"></label><label>Y<input type="number" step=".001" value="${d.y}" onchange="updateDiff('y',Number(this.value),true)"></label><label>半径<input type="number" step=".005" value="${d.radius||.04}" onchange="updateDiff('radius',Number(this.value),true)"></label></div></div><div class="panel-section"><button class="btn danger" style="width:100%" onclick="removeAnswer()">删除热点</button></div>`}
function selectAnswer(i){state.selected=i;document.querySelectorAll(".answer-item").forEach((x,n)=>x.classList.toggle("active",n===i));document.querySelectorAll(".hotspot").forEach((x,n)=>x.classList.toggle("selected",n===i));$("inspector").innerHTML=inspector()}
function updateLevelField(key,value){state.level[key]=value;markDirty()}
function updateDifficulty(value){state.level.difficulty=state.level.difficulty||{};state.level.difficulty.total=Number(value);markDirty()}
function updateDiff(key,value,rerender=false){state.level.differences[state.selected][key]=value;markDirty();if(rerender)renderEditor();else document.querySelectorAll(".answer-item")[state.selected].querySelector("b").textContent=state.level.differences[state.selected].label||state.level.differences[state.selected].id}
function markDirty(){setSave("有未保存修改",true);const status=$("editor-status");if(status)status.textContent="● 有未保存修改"}
function addAnswer(){const diffs=state.level.differences||(state.level.differences=[]);diffs.push({id:`answer_${diffs.length+1}`,shape:"circle",x:.5,y:.5,radius:.04,label:"新答案",era:"",explanation:"",difficulty:1,operation:"anachronism"});state.selected=diffs.length-1;markDirty();renderEditor();state.adding=true}
function removeAnswer(){if(!confirm("确定删除这个答案热点吗？"))return;state.level.differences.splice(state.selected,1);state.selected=Math.max(0,state.selected-1);markDirty();renderEditor()}
function canvasClick(event){if(!state.adding||event.target.classList.contains("hotspot"))return;const rect=$("level-image").getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)return;const d=state.level.differences[state.selected];d.x=+(Math.max(0,Math.min(1,(event.clientX-rect.left)/rect.width))).toFixed(4);d.y=+(Math.max(0,Math.min(1,(event.clientY-rect.top)/rect.height))).toFixed(4);state.adding=false;markDirty();renderEditor()}
function bindHotspotDrag(){document.querySelectorAll(".hotspot").forEach(el=>el.onpointerdown=e=>{e.stopPropagation();const i=Number(el.dataset.index);selectAnswer(i);el.setPointerCapture(e.pointerId);el.onpointermove=move=>{const rect=$("level-image").getBoundingClientRect(),d=state.level.differences[i];d.x=Math.max(0,Math.min(1,(move.clientX-rect.left)/rect.width));d.y=Math.max(0,Math.min(1,(move.clientY-rect.top)/rect.height));el.style.left=`${d.x*100}%`;el.style.top=`${d.y*100}%`;markDirty()};el.onpointerup=()=>{el.onpointermove=null;$("inspector").innerHTML=inspector()}})}
function toggleSafeZones(){document.querySelectorAll(".safe-zone").forEach(x=>x.hidden=!x.hidden)}
function fitImage(){$("level-image").style.maxHeight="calc(100vh - 160px)"}

async function saveLevel(status){
  try{setSave("保存中…");state.level.instruction=`圈出 ${state.level.differences.length} 个不属于这个年代的物件`;state.level.level_version=Number(state.level.level_version||1)+1;const seriesId=$("editor-series")?.value||state.series.id;await api(`/levels/${encodeURIComponent(state.level.level_id)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({series_id:seriesId,sort_order:state.levelEntry?.sort_order||10,status,runtime_json:state.level})});setSave("已保存",false);toast(status==="published"?"关卡已发布":"草稿已保存");await loadData();state.series=state.catalog.find(s=>s.id===seriesId);state.levelEntry=state.series?.levels.find(l=>l.id===state.level.level_id);renderEditor()}catch(e){setSave("保存失败",true);toast(e.message,"error")}}
function showPublishModal(){const l=state.level,d=l.differences||[],valid=d.every(x=>x.id&&x.label&&x.explanation&&x.x>=0&&x.x<=1&&x.y>=0&&x.y<=1);$("modal-root").innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-header"><h2>发布关卡</h2><button class="btn ghost" onclick="closeModal()">✕</button></div><div class="modal-body"><p><b>${escapeHtml(l.title)}</b> · v${Number(l.level_version)+1}</p><div class="checks"><div class="check">✓ 图片资源已配置</div><div class="check">✓ 图片比例 ${l.assets.width}:${l.assets.height}</div><div class="check">✓ ${d.length} 个答案热点</div><div class="check">${valid?"✓":"⚠"} 答案名称、解释与坐标校验</div></div><label style="display:grid;gap:6px;margin-top:16px">变更摘要<textarea id="publish-note" placeholder="说明本次修改内容"></textarea></label></div><div class="modal-footer"><button class="btn" onclick="closeModal()">取消</button><button class="btn primary" ${valid?"":"disabled"} onclick="closeModal();saveLevel('published')">确认并发布</button></div></div></div>`}
function showMobilePreview(){const a=state.level.assets.image;$("modal-root").innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-header"><h2>手机玩家预览</h2><button class="btn ghost" onclick="closeModal()">✕</button></div><div class="modal-body"><div class="mobile-preview"><div class="mobile-top"><span>‹</span><b>${escapeHtml(state.level.title)}</b><span>💡</span></div><div style="position:relative"><img src="${escapeHtml(a.url||a.local_path)}">${hotspots()}</div></div></div></div></div>`}
function closeModal(){$("modal-root").innerHTML=""}

function showSeriesModal(id=""){const s=state.catalog.find(x=>x.id===id)||{id:"",title:"",description:"",mode:"find_anachronism",cover_url:"",sort_order:10,enabled:true};$("modal-root").innerHTML=`<div class="modal-backdrop"><form class="modal" onsubmit="saveSeries(event)"><div class="modal-header"><h2>${id?"编辑":"新建"}系列</h2><button type="button" class="btn ghost" onclick="closeModal()">✕</button></div><div class="modal-body form-stack"><label>系列 ID<input id="series-id" value="${escapeHtml(s.id)}" ${id?"readonly":""} required></label><label>系列名称<input id="series-title" value="${escapeHtml(s.title)}" required></label><label>说明<textarea id="series-description">${escapeHtml(s.description)}</textarea></label><label>游戏模式<select id="series-mode"><option value="find_anachronism">寻找时代错置</option><option value="spot_difference">找不同</option></select></label><label>封面 URL<input id="series-cover" value="${escapeHtml(s.cover_url)}"></label><label><input id="series-enabled" type="checkbox" ${s.enabled?"checked":""}> 启用系列</label></div><div class="modal-footer"><button type="button" class="btn" onclick="closeModal()">取消</button><button class="btn primary">保存系列</button></div></form></div>`}
async function saveSeries(event){event.preventDefault();try{await api("/series",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:$("series-id").value,title:$("series-title").value,description:$("series-description").value,mode:$("series-mode").value,cover_url:$("series-cover").value,sort_order:10,enabled:$("series-enabled").checked})});closeModal();await loadData();renderSeries();toast("系列已保存")}catch(e){toast(e.message,"error")}}
function newLevel(seriesId=""){const series=state.catalog.find(s=>s.id===seriesId)||state.catalog[0];if(!series)return showSeriesModal();state.series=series;state.levelEntry={sort_order:(series.levels?.length||0)*10+10};state.level={schema_version:1,level_id:`level_${Date.now()}`,level_version:1,mode:series.mode,title:"未命名关卡",instruction:"圈出 5 个不属于这个年代的物件",assets:{image:{asset_id:"",url:"",sha256:"",bytes:0,content_type:"image/png"},width:1024,height:1536},differences:[],difficulty:{total:1}};state.selected=0;renderEditor()}
async function uploadLibraryAsset(file){if(!file)return;try{const id=`asset_${Date.now()}`,asset=await api(`/assets/${id}`,{method:"POST",headers:{"Content-Type":file.type},body:file});toast("素材上传成功");await loadData();renderLibrary();return asset}catch(e){toast(e.message,"error")}}
function renderReview(){shell("review","审核中心");const levels=state.catalog.flatMap(s=>s.levels||[]);$("view").innerHTML=`<div class="page"><div class="page-header"><div><h1>审核中心</h1><p>检查图片、热点位置与历史解释</p></div></div>${levelTable(levels)}</div>`}
function renderSettings(){shell("settings","系统设置");$("view").innerHTML=`<div class="page"><div class="page-header"><div><h1>系统设置</h1><p>环境与 API 连接</p></div></div><section class="card form-stack" style="max-width:600px"><label>Admin API<input id="settings-api" value="${escapeHtml(apiBase())}"></label><label>生产客户端 API<input value="在 client/project.godot 配置 oddspot/network/production_base_url" readonly></label><button class="btn primary" onclick="localStorage.setItem('oddspot_admin_api',$('settings-api').value);toast('设置已保存')">保存设置</button></section></div>`}

document.querySelectorAll(".nav-item").forEach(x=>x.onclick=()=>navigate(x.dataset.view));
$("api-base").value=apiBase();
$("logout").onclick=()=>{sessionStorage.removeItem("oddspot_admin_token");location.reload()};
$("login-form").onsubmit=async event=>{event.preventDefault();sessionStorage.setItem("oddspot_admin_token",$("token").value);localStorage.setItem("oddspot_admin_api",$("api-base").value.replace(/\/$/,""));try{await loadData();$("login").classList.add("hidden");renderOverview()}catch(e){sessionStorage.removeItem("oddspot_admin_token");toast(e.message,"error")}};
window.addEventListener("beforeunload",e=>{if(state.dirty){e.preventDefault();e.returnValue=""}});
if(token())loadData().then(()=>{$("login").classList.add("hidden");renderOverview()}).catch(()=>sessionStorage.removeItem("oddspot_admin_token"));
