const assert=require('assert')
const p=require('../js/core/puzzle')
assert.deepStrictEqual(p.createIdentityOrder(2,3),[0,1,2,3,4,5])
assert.deepStrictEqual(p.applyOperations(2,3,[{type:'swap',cells:[1,4]}]),[0,4,2,3,1,5])
assert.strictEqual(p.isSolved([0,1,2]),true)
assert.strictEqual(p.countMisplaced([0,2,1]),2)
assert.strictEqual(p.cellFromNormalizedPoint(.99,.99,2,3),5)
assert.deepStrictEqual(p.findHintSwap([0,4,2,3,1,5]),[1,4])
assert.strictEqual(p.validatePuzzleConfig({rows:2,cols:3,operations:[{type:'swap',cells:[0,3]},{type:'swap',cells:[1,4]},{type:'swap',cells:[2,5]}]}).ok,true)
assert.strictEqual(p.validatePuzzleConfig({rows:2,cols:3,operations:[{type:'swap',cells:[1,4]},{type:'swap',cells:[4,5]}]}).ok,false)
assert.strictEqual(p.validatePuzzleConfig({rows:2,cols:3,operations:[{type:'swap',cells:[1,4]}]}).ok,false)
assert.deepStrictEqual(p.puzzleGroups([3,4,2,0,1,5],2,3),[[0,1],[2,5],[3,4]])
assert.deepStrictEqual(p.movePuzzleGroup([3,4,2,0,1,5],2,3,0,3),[0,1,2,3,4,5])
